"use client";
import Head from "next/head";
import Script from "next/script";
import { useState } from "react";

const EfiJs = require("payment-token-efi");

export const Checkout = () => {
  const [state, setState] = useState({
    identificadorAccount: "6ecb42e5bbd4fc89de83fbb987047fe9",
    environment: "production",
    brandCard: "",
    numCartao: "",
    cvv: "",
    expirationMonth: "",
    expirationYear: "",
    reuse: false,
  });

  const checkBrand = () => {
    try {
      EfiJs.CreditCard.setCardNumber(state.numCartao)
        .verifyCardBrand()
        .then((brand) => {
          setState({ ...state, brandCard: brand });
          console.log("brand: ", brand);
        })
        .catch((err) => {
          console.log("erro ao checkBrand: ", err);
        });
    } catch (error) {
      console.log("erro ao checkBrand: ", error);
    }
  };
  const handleSubmit = async (event) => {
    event.preventDefault();

    await checkBrand();
    try {
      EfiJs.CreditCard.setAccount(state.identificadorAccount)
        .setEnvironment(state.environment) // 'production' or 'sandbox'
        .setCreditCardData({
          brand: state.brandCard,
          number: state.numCartao,
          cvv: state.cvv,
          expirationMonth: state.expirationMonth,
          expirationYear: state.expirationYear,
          reuse: state.reuse,
        })
        .getPaymentToken()
        .then((data) => {
          const payment_token = data.payment_token;
          const card_mask = data.card_mask;

          document.getElementById("paymentToken").innerHTML = payment_token;
          document.getElementById("cardMask").innerHTML = card_mask;

          console.log("payment_token", payment_token);
          console.log("card_mask", card_mask);
        })
        .catch((err) => {
          console.log("Código: ", err.code);
          console.log("Nome: ", err.error);
          console.log("Mensagem: ", err.error_description);
        });
    } catch (err) {
      console.log("Código: ", err.code);
      console.log("Nome: ", err.error);
      console.log("Mensagem: ", err.error_description);
    }
  };

  return (
    <>
      <Head>
         <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="https://cdn.jsdelivr.net/gh/efipay/js-payment-token-efi/dist/payment-token-efi.min.js" />

      <main className="bg-white">
      

        <div className="bg-white">
          <div className="w-full max-w-3xl mx-auto p-2">
            <div className="bg-white p-4 rounded-lg shadow-md border text-gray-600 ">
              <div className="mb-6">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label
                      htmlFor="first_name"
                      className="block mb-1"
                    >
                      First Name
                    </label>
                    <input
                      type="text"
                      id="first_name"
                      className="w-full rounded-lg border py-2 px-3 "
                    />
                  </div>
                  <div>
                    <label
                      htmlFor="last_name"
                      className="block mb-1"
                    >
                      Last Name
                    </label>
                    <input
                      type="text"
                      id="last_name"
                      className="w-full rounded-lg border py-2 px-3 "
                    />
                  </div>
                </div>

                <div className="mt-4">
                  <label
                    htmlFor="address"
                    className="block mb-1"
                  >
                    Address
                  </label>
                  <input
                    type="text"
                    id="address"
                    className="w-full rounded-lg border py-2 px-3 "
                  />
                </div>

                <div className="mt-4">
                  <label
                    htmlFor="city"
                    className="block mb-1"
                  >
                    City
                  </label>
                  <input
                    type="text"
                    id="city"
                    className="w-full rounded-lg border py-2 px-3 "
                  />
                </div>

                <div className="grid grid-cols-2 gap-4 mt-4">
                  <div>
                    <label
                      htmlFor="state"
                      className="block mb-1"
                    >
                      State
                    </label>
                    <input
                      type="text"
                      id="state"
                      className="w-full rounded-lg border py-2 px-3 "
                    />
                  </div>
                  <div>
                    <label
                      htmlFor="zip"
                      className="block mb-1"
                    >
                      ZIP Code
                    </label>
                    <input
                      type="text"
                      id="zip"
                      className="w-full rounded-lg border py-2 px-3 "
                    />
                  </div>
                </div>
              </div>

              <div>
                <h2 className="text-xl font-semibold mb-2">
                  Payment Information
                </h2>
                <div className="mt-4">
                  <label
                    htmlFor="card_number"
                    className="block mb-1"
                  >
                    Card Number
                  </label>
                  <input
                    type="text"
                    id="card_number"
                    placeholder="Num Cartao"
                    name="numCartao"
                    className="w-full rounded-lg border py-2 px-3 "
                    onChange={(event) =>
                      setState({ ...state, numCartao: event.target.value })
                    }
                  />
                </div>

                <div className="grid grid-cols-2 gap-4 mt-4">
                  <div >
                    <label
                      htmlFor="exp_date"
                      className="block mb-1"
                    >
                      Expiration Date
                    </label>
                    <div className="grid grid-cols-2 gap-2 ">

                    <input
                      type="text"
                      placeholder="Expiration Month"
                      name="expirationMonth"
                      className="w-12/12 rounded-lg border py-2 px-3 "
                      id="exp_date_month"
                      onChange={(event) =>
                        setState({
                          ...state,
                          expirationMonth: event.target.value,
                        })
                      }
                    />
                    <input
                      type="text"
                      placeholder="Expiration Year"
                      name="expirationYear"
                      className="w-12/12 rounded-lg border py-2 px-3 "
                      id="exp_date_year"
                      onChange={(event) =>
                        setState({
                          ...state,
                          expirationYear: event.target.value,
                        })
                      }
                    />
                    </div>
                  </div>
                  <div>
                    <label
                      htmlFor="cvv"
                      className="block mb-1"
                    >
                      CVV
                    </label>

                    <input
                      type="text"
                      placeholder="CVV"
                      onChange={(event) =>
                        setState({ ...state, cvv: event.target.value })
                      }
                      id="cvv"
                      className="w-full rounded-lg border py-2 px-3 "
                    />
                  </div>
                </div>
              </div>

              <div className="mt-8 flex justify-end">
                <button type="submit" onClick={handleSubmit}  className="text-white px-4 py-2 rounded-lg dark:text-white dark:hover:bg-[#4668dc90]  bg-[#4668dc] ">
                  Efetuar Pagamento
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};
